version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/lib/widgets/qu-howtos"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"
