<?php

add_filter( 'simple_register_taxonomy_settings', 'add_affiliate_management_metaboxes' );

function add_affiliate_management_metaboxes( $settings ) {
	$settings[] = array(
		'id'       => 'ms_directory_affiliate_management',
		'taxonomy' => array( 'ms_directory_affiliate_manager' ),
		'fields'   => array(
			array(
				'id'    => 'name',
				'label' => 'Name of the Affiliate manager',
				'type'  => 'text',
			),
			array(
				'id'    => 'picture',
				'label' => 'Picture',
				'type'  => 'image',
			),
			array(
				'id'    => 'phone',
				'label' => 'Phone number',
				'type'  => 'text',
			),
			array(
				'id'    => 'email',
				'label' => 'Email address',
				'type'  => 'text',
			),
			array(
				'id'    => 'linkedin',
				'label' => 'LinkedIn profile',
				'type'  => 'text',
			),
			array(
				'id'      => 'industry_focus',
				'label'   => 'Industry focus',
				'type'    => 'checklist',
				'options' => array(
					'administration'             => 'Administration, Business Support and Waste Management Services',
					'agriculture'                => 'Agriculture, Forestry, Fishing and Hunting',
					'finance_insurance'          => 'Finance and Insurance',
					'real_estate'                => 'Real Estate and Rental and Leasing',
					'transportation_warehousing' => 'Transportation and Warehousing',
					'retail'                     => 'Retail Trade',
					'professional_scientific'    => 'Professional, Scientific and Technical Services',
					'healthcare'                 => 'Healthcare and Social Assistance',
					'wholesale'                  => 'Wholesale Trade',
					'accommodation_food'         => 'Accommodation and Food Services',
					'utilities'                  => 'Utilities',
					'manufacturing'              => 'Manufacturing',
					'educational_services'       => 'Educational Services',
					'arts_entertainment'         => 'Arts, Entertainment and Recreation',
					'media_marketing'            => 'Media and Marketing',
					'software'                   => 'Software',
					'other'                      => 'Other',
				),
			),
			array(
				'id'    => 'countries',
				'label' => 'Which countries do you target with your affiliate programs?',
				'type'  => 'textarea',
			),
			array(
				'id'      => 'affiliate_software',
				'label'   => 'Which affiliate software do you usually use to manage your affiliates?',
				'type'    => 'checklist',
				'options' => array(
					'pap'           => 'Post Affiliate Pro',
					'affice'        => 'Affice',
					'affiliatewp'   => 'AffiliateWP',
					'afftrack'      => 'Afftrack',
					'avangate'      => 'Avangate',
					'awin'          => 'Awin',
					'cake'          => 'CAKE',
					'cjaffiliate'   => 'CJ Affiliate',
					'clickbank'     => 'Clickbank',
					'clickinc'      => 'Clickinc',
					'clickmeter'    => 'Clickmeter',
					'everflow'      => 'Everflow',
					'firstpromoter' => 'Firstpromoter',
					'growthhero'    => 'Growthhero',
					'hitpath'       => 'HitPath',
					'idevaffiliate' => 'iDevAffiliate',
					'jrox'          => 'JROX',
					'leaddyno'      => 'LeadDyno',
					'linktrust'     => 'Linktrust',
					'offer18'       => 'Offer18',
					'osiaffiliate'  => 'OSI affiliate',
					'rekuten'       => 'Rakuten Advertising',
					'redtrack'      => 'RedTrack',
					'refersion'     => 'Refersion',
					'scaleo'        => 'Scaleo',
					'shareasale'    => 'ShareASale',
					'tapaffiliate'  => 'Tapaffiliate',
					'tune'          => 'Tune',
					'trackiers'     => 'Trackiers',
					'voluum'        => 'Voluum',
					'other'         => 'Other',
				),
			),
			array(
				'id'    => 'all_programs',
				'label' => 'What are the names of all the affiliate programs that you manage?',
				'type'  => 'text',
			),
			array(
				'id'      => 'revenue',
				'label'   => 'Revenue',
				'type'    => 'radio',
				'options' => array(
					'usd10'  => '$10 000 - $20 000',
					'usd20'  => '$20 000 - $40 000',
					'usd40'  => '$40 000 - $60 000',
					'usd60'  => '$60 000 - $80 000',
					'usd80'  => '$80 000 - $100 000',
					'usd100' => '$100 000 +',
					'na'     => 'N/A',
				),
			),
			array(
				'id'      => 'compensation',
				'label'   => 'What kind of compensation do you receive for your work?',
				'type'    => 'radio',
				'options' => array(
					'salary'            => 'Fixed salary',
					'commission'        => 'Commission (performance based)',
					'salary_commission' => 'Salary + Commission',
					'na'                => 'N/A',
					'other'             => 'Other',
				),
			),
			array(
				'id'    => 'number_campaigns',
				'label' => 'What is the number of campaigns you manage?',
				'type'  => 'text',
			),
			array(
				'id'      => 'communication',
				'label'   => 'What communication channels do you use to communicate with affiliates?',
				'type'    => 'checklist',
				'options' => array(
					'email'    => 'Email',
					'livechat' => 'Live chat',
					'form'     => 'Contact form',
					'voip'     => 'VoIP',
					'phone'    => 'Phone calls',
					'social'   => 'Social media',
					'other'    => 'Other',
				),
			),
		),
	);

	return $settings;
}
