name: Add PR to the Project

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add PR to the Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Add PR to Project
        run: gh project item add --project "25" --content-id "${{ github.event.pull_request.node_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_CICD_PAT }}
