name: Release Nightly

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-nightly'

jobs:
  build:
    name: 1️⃣ Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'

      - name: Install Composer Dependencies
        run: composer install

      - name: Build All CSS and JS
        run: yarn build:all

      - name: Remove Unnecessary Files [theme]
        run: rm -rf node_modules vendor .git .idea .github .husky *.md *.lock .editorconfig .eslintignore .eslintrc .gitignore .stylelintrc composer.json gulpfile.js commitlint.config.js package.json phpcs.xml

      - name: Remove Unnecessary Files [qu-howtos]
        working-directory: ./lib/widgets/qu-howtos/
        run: rm -rf node_modules package.json yarn.lock webpack.config.js

      - name: Get the Version
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: ".*/([^/]+)$"

      - name: Create a ZIP File
        run: zip -r postaffiliatepro_${{ steps.version.outputs.group1 }}.zip .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: true
          body: See changes in the [CHANGELOG.md](CHANGELOG.md)
          generate_release_notes: true
          append_body: true
          files: ./postaffiliatepro_${{ steps.version.outputs.group1 }}.zip
